const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const revealObserver=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}})},{threshold:.12,rootMargin:'0px 0px -5% 0px'});
document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const menuButton=document.querySelector('.menu-toggle');const nav=document.querySelector('.nav');menuButton?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});document.querySelectorAll('.nav a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menuButton?.setAttribute('aria-expanded','false')}));
const gallery=document.querySelector('.project-gallery');
if(gallery){let down=false,startX=0,scrollStart=0;gallery.addEventListener('pointerdown',e=>{down=true;startX=e.clientX;scrollStart=gallery.scrollLeft;gallery.setPointerCapture?.(e.pointerId)});gallery.addEventListener('pointermove',e=>{if(!down)return;gallery.scrollLeft=scrollStart-(e.clientX-startX)});gallery.addEventListener('pointerup',()=>down=false);gallery.addEventListener('pointercancel',()=>down=false)}
const cards=[...document.querySelectorAll('.gallery-image-card')];const lightbox=document.querySelector('.lightbox');const lightboxImage=document.querySelector('.lightbox-image');const lightboxCaption=document.querySelector('.lightbox-caption');let current=0;
const showLightbox=(index)=>{if(!cards.length)return;current=(index+cards.length)%cards.length;const card=cards[current];lightboxImage.src=card.dataset.full;lightboxImage.alt=card.querySelector('img')?.alt||'';lightboxCaption.textContent=card.dataset.caption||'';lightbox.classList.add('is-open');lightbox.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'};
const closeLightbox=()=>{lightbox.classList.remove('is-open');lightbox.setAttribute('aria-hidden','true');document.body.style.overflow=''};
cards.forEach((card,index)=>card.addEventListener('click',()=>showLightbox(index)));document.querySelector('.lightbox-close')?.addEventListener('click',closeLightbox);document.querySelector('.lightbox-prev')?.addEventListener('click',()=>showLightbox(current-1));document.querySelector('.lightbox-next')?.addEventListener('click',()=>showLightbox(current+1));lightbox?.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});window.addEventListener('keydown',e=>{if(!lightbox?.classList.contains('is-open'))return;if(e.key==='Escape')closeLightbox();if(e.key==='ArrowLeft')showLightbox(current-1);if(e.key==='ArrowRight')showLightbox(current+1)});
if(!reduceMotion&&window.matchMedia('(pointer:fine)').matches){const dot=document.querySelector('.cursor-dot');const ring=document.querySelector('.cursor-ring');let x=innerWidth/2,y=innerHeight/2,rx=x,ry=y;window.addEventListener('pointermove',event=>{x=event.clientX;y=event.clientY;dot.style.transform=`translate(${x}px, ${y}px) translate(-50%, -50%)`});const renderCursor=()=>{rx+=(x-rx)*.14;ry+=(y-ry)*.14;ring.style.transform=`translate(${rx}px, ${ry}px) translate(-50%, -50%)`;requestAnimationFrame(renderCursor)};renderCursor();document.querySelectorAll('a,button,.project,.experience-row').forEach(el=>{el.addEventListener('mouseenter',()=>ring.classList.add('is-hover'));el.addEventListener('mouseleave',()=>ring.classList.remove('is-hover'))});document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('pointermove',event=>{const rect=el.getBoundingClientRect();const dx=event.clientX-(rect.left+rect.width/2),dy=event.clientY-(rect.top+rect.height/2);el.style.transform=`translate(${dx*.18}px, ${dy*.18}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}
if(!reduceMotion){const hero=document.querySelector('.hero-copy');window.addEventListener('scroll',()=>{if(window.scrollY<innerHeight)hero.style.transform=`translateY(${window.scrollY*.045}px)`},{passive:true})}
